feat: custom dictionaries
algolia/algoliasearch-client-python pull request #522
Opened 2021-04-22 08:39 UTC by chloelbn

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no
| Related Issue     | Fix #519
| Need Doc update   | no

## Describe your change

Adds the custom dictionaries methods and their tests

2021-04-23 13:11 UTC, tkrugg commented on algoliasearch/search_client.py
> +    # # # # # # # # # # # # # # # # # # # # #
```suggestion
```

I don't this see pattern of commenting anywhere. Is this new?

2021-04-23 13:13 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:13 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:13 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:14 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:14 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:14 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:14 UTC, tkrugg commented on algoliasearch/search_client.py
> +    #
```suggestion
```

The function is well name enough that we shouldn't need this comment to understand what it does. I'll suggest we remove this comment.

2021-04-23 13:17 UTC, tkrugg commented on tests/features/test_search_client.py
> +        entry_id = "".join(random.choice(string.ascii_letters) for i in range(10))
In general, it's best to make tests as deterministic as possible, meaning avoid anything involving `random` if not necessary.
 I'd rather see here: `entry_id = 'some string'`

Not that it's a problem here,

2021-04-23 13:32 UTC, chloelbn commented on tests/features/test_search_client.py
> +        entry_id = "".join(random.choice(string.ascii_letters) for i in range(10))
we had too because those tests are happening on app level, and conflicts might arise while the other tests or even the other clients are running their tests in the same time

2021-04-23 13:45 UTC, tkrugg commented on tests/features/test_search_client.py
> +        self.assertEqual(client.get_dictionary_settings(), stopwords_settings)
I think the request parameter request_options is never tests. I know practically just passed through it can still be lost. Is there a solid reason not to test it?

2021-04-23 13:47 UTC, chloelbn commented on tests/features/test_search_client.py
> +        self.assertEqual(client.get_dictionary_settings(), stopwords_settings)
I believe it's tested on some other level on the test suite. As it doesn't contain options solely used in this feature they don't need to be tested IMHO. What's your take on this?

2021-04-23 13:50 UTC, tkrugg commented on algoliasearch/search_client.py
> +        return self.replace_dictionary_entries(dictionary, [], request_options)
I'm a little confused here: If I understand correctly, clear_directionary_entries is supposed to delete all the entries. 
but the implem suggest that it's calling replace on an empty array, which returns does:


```py 
"requests": build_raw_response_batch("addEntry", []),
```

but does this actually delete existing entries?

2021-04-23 13:55 UTC, tkrugg commented on algoliasearch/search_client.py
> +        return self.replace_dictionary_entries(dictionary, [], request_options)
nevermind

2021-04-23 14:03 UTC, chloelbn commented on algoliasearch/search_client.py
> +        return self.replace_dictionary_entries(dictionary, [], request_options)
here is the implem of `replace_dictionary_entries`
```
    def replace_dictionary_entries(
        self, dictionary, dictionary_entries, request_options=None
    ):
        # type: (str, List[dict], Optional[Union[dict, RequestOptions]]) -> DictionaryResponse # noqa: E501

        raw_response = self._transporter.write(
            Verb.POST,
            endpoint("1/dictionaries/{}/batch", dictionary),
            {
                "clearExistingDictionaryEntries": True,
                "requests": build_raw_response_batch("addEntry", dictionary_entries),
            },
            request_options,
        )

        return DictionaryResponse(self, raw_response)
```
I believe it behaves the same way, but I may be missing something (that coffee never kicks in damn)

2021-04-23 14:54 UTC, tkrugg commented on algoliasearch/search_client.py
> +            Verb.PUT, "1/dictionaries/*/settings", dictionary_settings, request_options
The type here is maybe wrong? I [see other clients consider dictonnary_settings to be an object/hash.](https://github.com/algolia/algoliasearch-client-javascript/pull/1253/files#diff-258661e24e3ccf4aa470004bbb61c413d42ef12d1a8f8dc9c9aba1d2c951c092R4-R11)


Here it seems to be a `List[dict]`. is this correct?

2021-04-23 14:58 UTC, tkrugg commented on tests/features/test_search_client.py
> +        self.assertEqual(client.get_dictionary_settings(), stopwords_settings)
I don't want to be overzealous. I tend to think about tests answering the question: _if my method for some reason stops passing over the `request_options`, will I be notified via a breaking test_. This test or another. 
If it's already the case, nevermind.

2021-04-29 10:07 UTC, tkrugg requested changes
we just need to fix the type and we're good to go

2021-04-29 10:07 UTC, tkrugg commented on tests/features/test_search_client.py
> +        self.assertEqual(client.get_dictionary_settings(), stopwords_settings)
resolving this

2021-04-30 09:54 UTC, tkrugg approved these changes

2021-04-30 09:57 UTC, merged